Repository tudat-team/tudatpy, pull requests merged in 2024-10, with the labels that each got.

#178 Nightly bump version workflow
  .github/workflows/bump_dev_version_nightly.yml
Labels: enhancement

#175 Use tudatpy conda package to build docs on Read the Docs
  .readthedocs.yml
  docs/environment_readthedocs.yaml
  docs/source/conf.py
Labels: documentation-related

#182 Fix bump version workflow
  .github/workflows/bump_dev_version_nightly.yml
Labels: bug

#179 Render python native docs on API docs website
  docs/source/ephemeris.rst
  docs/source/gravity_field.rst
  docs/source/propagation.rst
  tudatpy/numerical_simulation/propagation/dependent_variable_dictionary/dependent_variable_dictionary.py
Labels: documentation-related

#156 fix(python3.12): Update Python setup script to use sysconfig
  cmake/YACMAPythonSetup.cmake
Labels: bug
